### ISSUE TITLE
Deposterize filter

### ISSUE THREAD

**Issue by ADormant** [tapcio/PeteOpenGL2Tweak#1]
Effect is subtle but helps mitigate posterization.

https://github.com/gonetz/GLideN64/commit/78d7c99b029deb5a17869a8254f4c44fd76edf0c
http://blog.metaclassofnil.com/?p=306

**Comment by Nucleoprotein** [comment]
1ded43eedc2f87392c91b7efc7ada1a1d90629ab

**Comment by ADormant** [comment]
@tapcio Thank you very much.

I'm not sure but PPSSPP may have a better xBRZ texture cache so possibly something may be worthwhile to copy from there.

https://github.com/hrydgard/ppsspp/tree/master/ext/xbrz
