### ISSUE TITLE
use expand screen width for enhace widescreen

### ISSUE THREAD

**Issue by overlordchaos** [tapcio/PeteOpenGL2Tweak#11]
the original plug in, has under special game fixes, an option called "expand screen width" to make the games render more areas. this can be used to make games render in widescreen since the option partially works since its to fix games not rendering fully at 4:3 if this can be implemented to order the gpu to render in 16:9 with the other widescreen hacks/fixes it would truly revolutionize the emulation

**Comment by Nucleoprotein** [comment]
I dont think is possible, and also this plugin is dead, i will not develop anything new here.
Everyone should just use Duckstation now for PS1 emulation, there is not better emu out there.

**Comment by overlordchaos** [comment]
> I dont think is possible, and also this plugin is dead, i will not develop anything new here.
> Everyone should just use Duckstation now for PS1 emulation, there is not better emu out there.

sorry but duckstation has good stuff and really bad stuff. your plug in its a unique marvelous thing after the original pete's plug in. it is possible since if you mod that option to order the emulator to expand the emulation area even further, you would deliver something not even duckstation can do atm.

**Comment by Nucleoprotein** [comment]
Duckstation is better in **everything** than PCSX or ePSXe with PeteOpenGL2Tweak can offer, there is no bad stuff, i use it myself.
But if you want to extend this plugin feel free to fork the code.

**Comment by overlordchaos** [comment]
> Duckstation is better in **everything** than PCSX or ePSXe with PeteOpenGL2Tweak can offer, there is no bad stuff, i use it myself.
> But if you want to extend this plugin feel free to fork the code.

can you at least do a final release with all the changes you did?

**Comment by Nucleoprotein** [comment]
iCatButler released fully featured plugin in his PCSX fork and over ngemu forums

**Comment by overlordchaos** [comment]
> iCatButler released fully featured plugin in his PCSX fork and over ngemu forums

yeah pcsxr its what i use and no i needed to get the plug in elsewhere. he has pretty much abandoned the project as you to praise duckstation. duckstation is a garbage emulator that has a nice UI and some cool upgrades over the advantage of forgetting about plug ins. they refuse to give PEC support since their emulator has a cheat system that is garbage. again would you do a FINAL compile over all the changes you did from the initial release? its not fair your hard work goes to the toilet just because you are praising the duckstation....

**Comment by Nucleoprotein** [comment]
"FINAL compile" will be the same as included in iCatButler PCSX, if you want just compile it yourself.
