### ISSUE TITLE
Multi-pass CPU-based filter framework

### ISSUE THREAD

**Issue by ADormant** [tapcio/PeteOpenGL2Tweak#3]
Is that possible? Hylian mentioned that Super xBR could be used as a texture filter but needs multi-pass filter framework.

**Comment by ADormant** [comment]
https://drive.google.com/file/d/0B_yrhrCRtu8GYkxreElSaktxS3M/view?pref=2&pli=1
Super xBR on textures looks phenomenal on digitized games and games with pre-rendered backgrounds.
Here are screenshots of RE Remake on GC with Super xBR applied with RetroArch's image viewer core.
![retroarch-0104-045603c2lwi](https://cloud.githubusercontent.com/assets/10523326/12136881/4974021c-b44c-11e5-8611-b333008b11f7.png)
![retroarch-0104-045626t3yf9](https://cloud.githubusercontent.com/assets/10523326/12136887/53f015b4-b44c-11e5-853e-18b585491b1f.png)
![retroarch-0104-050239cgzx3](https://cloud.githubusercontent.com/assets/10523326/12136892/5b4e5adc-b44c-11e5-9391-898f64299610.png)
![retroarch-0104-050309hrlvx](https://cloud.githubusercontent.com/assets/10523326/12137288/6826473a-b44f-11e5-862f-b0f4bb41b852.png)
![retroarch-0104-045826iplny](https://cloud.githubusercontent.com/assets/10523326/12137295/805b4b8e-b44f-11e5-985d-b7640ea6ac13.png)

**Comment by Nucleoprotein** [comment]
Multi-pass means multi pass shaders, Tweak is not using shaders because can't access OpenGL render state.
Tweak as it's not normal plugin but a hack to different one, and all limitation of original plugin apply to it (like OpenGL2). For such filter/option I think you require new GPU plugin or better - new PSX emulator.

**Comment by ADormant** [comment]
No I meant multi-pass filter framework for cpu based super xbr according to Hylian that should be possible but perhaps not in a hack like this.
http://ngemu.com/threads/peteopengl2tweak-tweaker-for-peteopengl2-plugin-w-gte-accuracy-hack.160319/page-29
@tapcio

**Comment by Nucleoprotein** [comment]
I don't know what he mans by "multipass framework" because it's pretty simple - multi-pass shaders are applied in order, so it need to be applied in same order after re-writting them to C++ code... Super-xBR from RetroArch is 5 or 6 pass shader so it will be -ultra- slow when rewritten to C++. Current 6xBRZ + deposterize is -very- slow...

**Comment by ADormant** [comment]
@tapcio Base Super xBR is 2 passes then 4x Super xBR is 4 passes then 8 etc. I think 4x Super xBR would be playable with high-end CPU.
https://drive.google.com/file/d/0B_yrhrCRtu8GYkxreElSaktxS3M/view?pref=2&pli=1

**Comment by ADormant** [comment]
@tapcio C based Super xBR
http://pastebin.com/cbH8ZQQT

**Comment by Nucleoprotein** [comment]
I have seen that, but I do not have time to add it yet, maybe in weekend, also it's limited to 2x scaling.

**Comment by ADormant** [comment]
Would be possibe to add 4x at least?

**Comment by ADormant** [comment]
https://dropfile.to/SlPGs

**Comment by Nucleoprotein** [comment]
Not my thing:
`default: ERROR_LOG(VIDEO, "Super-xBR upsampling only implemented for factor 2");`

**Comment by ADormant** [comment]
@tapcio 
For 4x you should be able to run Super xBR twice does it work for you?

**Comment by ADormant** [comment]
@tapcio 
Super xBR scaler https://forums.dolphin-emu.org/attachment.php?aid=14516
http://pastebin.com/cbH8ZQQT
https://drive.google.com/file/d/0B_yrhrCRtu8GYkxreElSaktxS3M/view?pref=2&pli=1
