### ISSUE TITLE
fix GTE widescreen hack for 1080p

### ISSUE THREAD

**Issue by overlordchaos** [tapcio/PeteOpenGL2Tweak#6]
i have a powerful pc that can do 1080p psx emulation with several filters and shaders to reach 1080p quality levels. my problem its the the GTE widescreen hack on 1080p leaves on the sides openings where the GPU stops rendering the game since it is consider off screen. will leave a vigilante 8 second offense shot so you see what i mean. its not like an option or a fix to do a real full screen on 1080p? this also happens in pretty much all the games. in digimon rumble arena if the characters goes too distant from one to the other, some of their body parts dissapear and when they go one near the other they re appear.
![epsxe 2016-03-25 02-50-33-583](https://cloud.githubusercontent.com/assets/18064513/14038816/6170df9a-f234-11e5-9604-f7a7fa3e6db6.jpg)

**Comment by Nucleoprotein** [comment]
This is not fixable, GTE widescreen is a -hack- and some games will clip geometry at sides, this is completely normal.

PS: PCSX2 solution for forcing widescreen in some PS2 games is to patch -game- code. This is completely different solution as PS2 can display games in widescreen resolutions.

**Comment by overlordchaos** [comment]
may i ask, its not possible to fix the hack to expand the drawing screen width?

**Comment by Nucleoprotein** [comment]
Game is clipping geometry so you really need **hack game code** not plugin/emu.
Also doing this without some virtual PSX CPU overclock can cause slowdowns.

**Comment by overlordchaos** [comment]
well the expand screen width under special options in the original plug in expanded the screen as in your version its always on. i always imagined that this hack could be modified so the screen width its recognized by the emulator or plug in and expand it a bit more. it is also interesting nobody ever has done a psx emulator with cpu overclocking. all the other emulator has this feature...

**Comment by Nucleoprotein** [comment]
"Expand width" special game option is to expand visible area of window to show overscan area. CRT TVs have overscan: https://en.wikipedia.org/wiki/Overscan and some CAPCOM fighting games uses this area to expand screen. Without this option screen will be cropped in that games.
That option is not for additional rendering, it only shows about 50 pixels more in width.

**Comment by overlordchaos** [comment]
"Expand width" special game option its what i am asking if you can check it out to expand it further since thats what it is affecting the empty areas in many games as the one that i have showed you.
i guess its set up to expand to widescreen on 720p perhaps if you tweak the game option to 1080p this will not appear anymore. in the original plug in if you use widescreen even with GTE hack on the emulator without that option the emulator will only render the center of the screen as the videos appear on youtube when they are 4:3 but instead of black bars at the sides empty areas.

i think if you check the values of that game option to expand the area (even if you do need to do a new option so it does not waste resources on 720p and lower resolutions) will fix this nasty side holes on many games.

**Comment by Nucleoprotein** [comment]
For god sake, re-read what I written above, check wiki about overscan ect. because:
**-EXPAND WIDTH WILL NOT RENDER MORE POLYGONS-**
That option shows only overscan area. For such games like on screenshot use pillarboxing.

**Comment by overlordchaos** [comment]
well if you are sure... i mean the expand screen width to me it renders more polygons but if you are sure i will not argue with you. just guessing that option may or may not modify some others configs of the plug in expanding in total the screen width. but i may just need to learn to live with this issue.

**Comment by Nucleoprotein** [comment]
Pete code for that options is more cruel I though. It changes 368 display width to 384... ie. it's a hack, not proper overscan.

**Comment by overlordchaos** [comment]
lol i guess he did a hack fix hundreds of years ago when i contacted him directly and notify him that digimon rumble arena with the same game option we are discussing the game was not rendering properly not the backround or the polygons of the characters. he did fix it. sure this was in times 720p was not achieved in emulation since it would look awfully pixelated and a pentium 4 could not render such a thing with a 256 mbs ram for the tiny gpu we used back in those days...

too bad he is missing apparently. if he was still around perhaps he could fix it or do a new gpu plug in entirely based upon this one.

**Comment by Nucleoprotein** [comment]
Most PSX emulators and plugins including Petes does not emulate most thing correctly, most thing was guessed not tested on real hardware, look at test here: http://emulation.gametechwiki.com/index.php/PS1_Tests .We really need new emulator like Dolphin for PSX.
PS: ePSXe 2.0 was much improved.
EDIT: Upps, they tested interpreter mode in ePSXe 2.0 ... not dynamic recompiler.

**Comment by overlordchaos** [comment]
yeah my question its why everyone abandoned the psx emulation? its one of the best ever consoles and nobody pays any attention to it...

**Comment by ADormant** [comment]
@overlordchaos 
There is a new PSX emulator under development
https://github.com/simias/rustation

**Comment by overlordchaos** [comment]
@ADormant where can i download a windows working copy?
this will fix widescreen issues? it would be nice!

**Comment by overlordchaos** [comment]
@tapcio have you ever tried to raise the number of 384 to 420? that would crash the emulator? cause maybe if you expand that number, the polygons will be rendered. just an idea. i think pete`s did something like that when i reported the error many years ago.

**Comment by ADormant** [comment]
@overlordchaos 
Try retroarch http://buildbot.libretro.com/ but this emulator is in too early development to be playable.

**Comment by ADormant** [comment]
@overlordchaos You can test this https://drive.google.com/file/d/0Bz8IYcLfu84zdTNhZ2xmQm10Q0k/view?pref=2&pli=1

**Comment by Nucleoprotein** [comment]
I compiled that fork of PCSXR yesterday, it crashes or displays black screen for me.

**Comment by overlordchaos** [comment]
@tapcio PCSXR yeah it crashes. does the video plug in compilation has anything different to it than a regular one? so i can test it out with a working PCSXR if you want to.

**Comment by overlordchaos** [comment]
@tapcio btw your tweaked version the one i found online and the one you asked me to test out with that PCSXR version gives me corrupt video. will leave a shot of vigilante 8 second offense since i left a picture. also noticed the previous screenshot was made with another version of the plug in not yours. i am detecting an issue. perhaps something uncompatible with my video card?

**Comment by Nucleoprotein** [comment]
This is not my work, this is compiled fork from here: https://github.com/iCatButler/pcsxr and you need to use both, plugin and include pcsxr at once. Also is not related to GTE Widescreen hack.

**Comment by overlordchaos** [comment]
@tapcio using both thogether i get the same issue as you. error report on the second the emulator tries to boot. and there is no video at all.

**Comment by Nucleoprotein** [comment]
I didn't ask you to test anything, @ADormant asked.
I do not know also why iCatButler used old PCSX-R version as base, is about 23 changes behind. https://pcsxr.codeplex.com/SourceControl/list/changesets

**Comment by overlordchaos** [comment]
@tapcio sorry lol read it fast.
@ADormant it does not work. no video and error report on the booting attempt from the emulator.
@tapcio i am getting this corrupted video from all the games i try with your plug in:
![pcsxr 2016-03-27 14-22-02-187](https://cloud.githubusercontent.com/assets/18064513/14066696/4fba9558-f427-11e5-967d-ce52b6a2b6ac.jpg)

**Comment by Nucleoprotein** [comment]
Please not write here about obvious things, use forum. Also this is caused by your improper configuration, read first post in forum thread ie. here: http://ngemu.com/threads/peteopengl2tweak-tweaker-for-peteopengl2-plugin-w-gte-accuracy-hack.160319/

**Comment by overlordchaos** [comment]
@tapcio can you point out to me or give me a link for the forum? tyvm.

**Comment by overlordchaos** [comment]
@tapcio wow thats a difference. yet still i see some graphical glitches. for the image filtering there is a shaders pack you can include and will do magic for the imagery. if you want i can show you some screenshot.
