### ISSUE TITLE
Crash Bash, Spyro and CTR doesn't work :P

### ISSUE THREAD

**Issue by NetyashaRoozi** [tapcio/PeteOpenGL2Tweak#9]
I tested Crash Bash, all 3 spyro ps1 games and CTR and they don't work correctly for me, Spyro games crash when entering any portal, Crash Bash crashes after the loading screen to the warp room and CTR crashes right before the naughty dog box is shown, I hope these somehow get fixed :\

**Comment by Nucleoprotein** [comment]
You should use iCatButler fork with PCSX-R PGXP because this is outdated.

**Comment by NetyashaRoozi** [comment]
ah, I am guessing the source code is made in visual studio so I can compile it

**Comment by Nucleoprotein** [comment]
Here: https://github.com/iCatButler

**Comment by Harley201** [comment]
Just tested it and I had to fix one line of code (very easy fix) and just tested CTR and Spyro 3. When I load into my save I am located in Cloud Spires and it crashes before I can actually get into the game, CTR doesn't crash the emulator but it still gets stuck before the box shows up, could be pcsxr so I am going to test the emulator without the plugin

**Comment by NetyashaRoozi** [comment]
Sorry about that I ran the wrong plugin :P

**Comment by NetyashaRoozi** [comment]
The emulator wont run now :\ it gives me a error saying line 1185 is out of range

**Comment by Nucleoprotein** [comment]
Then use builds from ngemu forums: http://ngemu.com/threads/peteopengl2tweak-tweaker-for-peteopengl2-plugin-w-gte-accuracy-hack.160319/page-69#post-2508721

**Comment by NetyashaRoozi** [comment]
Just tested the build, pcsxr-pgxp.exe crashes when loading a rom and the plugin with normal pcsxr still crashes when loading Spyro 3 and freezes when loading CTR

**Comment by Nucleoprotein** [comment]
Then you doing something wrong... register on ngemu forums and ask for help there.

**Comment by NetyashaRoozi** [comment]
k
